version: "3"

services:
  front:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    ports:
      # 8080 为宿主机访问前端服务地址
      - "${HOST_FRONT_PORT}:80"
    volumes:
      # 配置文件，按需修改其中的 `proxy_bypass` 路径
      # 后期如果后端服务也容器化，则该路径可以直接替换为后端服务容器
      - ./nginx.conf:/etc/nginx/conf.d/default.conf nn-front:prod-v1

  fs:
    image: nginx
    ports:
      # 为宿主机访问地址，用于浏览器访问下载
      - "${HOST_FS_PORT}:80"
    volumes:
      # 冒号前的路径地址为宿主机目录，后端服务将文件保存至该路径（该路径按需修改）
      # 后期如果后端服务也容器化，则此处可以使用共享卷
      - ${HOST_FILE_PATH}:/files
      # 配置文件
      - ./file-nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    driver: bridge
